name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > AI-Banks.pem
        chmod 600 AI-Banks.pem
        # Test SSH connectivity with disabled strict host key checking
        ssh -o StrictHostKeyChecking=no -i AI-Banks.pem -p 1613 $EC2_USER@$EC2_HOST "echo 'SSH connection successful'"
        
        # Create folder on EC2 server and copy application file
        ssh -o StrictHostKeyChecking=no -i AI-Banks.pem -p 1613 $EC2_USER@$EC2_HOST "mkdir -p /home/$EC2_USER/TESTING_api"
        scp -o StrictHostKeyChecking=no -i AI-Banks.pem -P 1613 -r ./* $EC2_USER@$EC2_HOST:/home/$EC2_USER/TESTING_api
        
        # SSH into EC2 server and activate base environment before running Flask app
        ssh -o StrictHostKeyChecking=no -i AI-Banks.pem -p 1613 $EC2_USER@$EC2_HOST << 'EOF'
        
        
        # Load conda environment
        source ~/.bashrc
        # conda env list
        # conda activate base

        # python --version

        # cd /home/ubuntu/TESTING_api
        # # Run Flask apps
        nohup python testing.py &